services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        volumes:
            - .:/app
            - /app/node_modules
        restart: unless-stopped

    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        volumes:
            - .:/app
            - /app/node_modules
        restart: unless-stopped
        command: npm run dev
